<?php

// SECURITY: Don't allow direct calls to this file outside the context of HelpSpot
if (!defined('cBASEPATH')) die();

/* EDITING NOTES
1. Some strings contain %s symbols, these must be maintained
2. Any single quotes must be preceded by a slash like this:  \'  ex: there\'s
3. If you modify this file, be sure to back it up in case you overwrite it during an upgrade by accident
*/

define('lg_admin_settings_title','HelpSpot instellingen');
define('lg_admin_settings_savebutton','Instellingen opslaan');
define('lg_admin_settings_saved','Instellingen opgeslagen');
define('lg_admin_settings_on','Aan');
define('lg_admin_settings_off','Uit');
define('lg_admin_settings_hsauth','HelpSpot intern');
define('lg_admin_settings_blackbox','Black Box');
define('lg_admin_settings_usernamenotset','Uw account heeft geen username. Een username is vereist om in te kunnen loggen met Black Box authenticatie. Let bovendien op het instellen van de usernames van andere medewerkers, anders zullen zij niet in kunnen loggen.');
define('lg_admin_settings_blackboxwarn','U heeft BlackBox-base.php niet hernoemd naar BlackBox.php. Hernoem het bestand en verzeker uzelf ervan dat Black Box ingericht voor gebruik in deze installatie.');
define('lg_admin_settings_blackboxdesc','Black Box authenticatie maakt het mogelijk op een eigen functie te creeeren waarmee Helpspot users kunnen inloggen met een single sign on. Om dit te gebruiken moet u de functie inrichten in custom_code/BlackBox- base.php 
											hernoem het bestand BlackBox.php, en sla de instellingen op in Black Box.');
define('lg_admin_settings_auth','Authenticatie');
define('lg_admin_settings_sesstimeout','Sessie timeout');
define('lg_admin_settings_authtype','Authenticatie type');
define('lg_admin_settings_sesstimeoutex','Duur van de sessie login voordat de user uitgelogd wordt');
define('lg_admin_settings_ldap','LDAP/Active Directory');
define('lg_admin_settings_ldap_accountsuffix','Account achtervoegsel');
define('lg_admin_settings_ldap_accountsuffix_ex','Het accountachtervoegsel voor uw domein, bijvoorbeeld: @mydomain.local');
define('lg_admin_settings_ldap_basedn','Base DN');
define('lg_admin_settings_ldap_basedn_ex','bijvoorbeeld: DC=mydomain,DC=local');
define('lg_admin_settings_ldap_dn_control','Domain Controller');
define('lg_admin_settings_ldap_dn_control_ex','bijvoorbeeld: dc01.mydomain.local');
define('lg_admin_settings_ldap_username','Admin username');
define('lg_admin_settings_ldap_username_ex',"Een domein admin username is vereist om een verbinding te kunnen maken.");
define('lg_admin_settings_ldap_password','Admin password');
define('lg_admin_settings_ldap_password_ex',"Het password voor de domein admin");
define('lg_admin_settings_ldap_usessl','Gebruik SSL');
define('lg_admin_settings_ldap_usessl_ex','Gebruik SSL (LDAPS), uw server moet hiervoor ingericht zijn. PHP vereist dat OpenSSL geinstalleerd is. Zie: <a href="http://adldap.sourceforge.net/wiki/doku.php?id=ldap_over_ssl" target="_blank">http://adldap.sourceforge.net/wiki/doku.php?id=ldap_over_ssl</a>');
define('lg_admin_settings_ldap_usetls','Gebruik TLS');
define('lg_admin_settings_ldap_noldap','Op uw server is de PHP LDAP library niet geinstalleerd. Dat is wel vereist om dit type authenticatie te kunnen gebruiken.');
define('lg_admin_settings_ldap_usernamenote','De LDAP/AD usernames van uw medewerkers moeten ingevoerd zijn in hun HelpSpot instellingen om in te kunnen loggen');
define('lg_admin_settings_ldap_username','Username');
define('lg_admin_settings_ldap_password','Password');
define('lg_admin_settings_ldap_testing','Bezig met testen...');
define('lg_admin_settings_ldap_test','LDAP instellingen testen');
define('lg_admin_settings_ldap_testbtn','Test');
define('lg_admin_settings_system','Systeem');
define('lg_admin_settings_timetracking','Time Tracker');
define('lg_admin_settings_timetrackingon','Time Tracker ingeschakeld');
define('lg_admin_settings_spellchecking','Spellngscontrole');
define('lg_admin_settings_securityip','IP\'s die geautoriseerd zijn om tasks.php/tasks2.php aan te roepen');
define('lg_admin_settings_securityipdesc','Scheidt meerdere IP\'s met een comma. Opmerking: leeg laten betekent toestemming voor alle IP adressen.');
define('lg_admin_settings_spamlinkct','Links tellen voor SPAM');
define('lg_admin_settings_spamlinkctdesc','Forumberichten en aanvragen van de portaal die meer dan dit aantal links bevatten worden automatisch als SPAM aangemerkt');
define('lg_admin_settings_spamautodel','SPAM automatisch verwijderen');
define('lg_admin_settings_spamautodeldesc','Aanvragen en forumberichten met een SPAM waarschijnlijkheid hoger dan of gelijk aan deze waarde worden automatisch verwijderd');
define('lg_admin_settings_spamtimeip','Formulier tijd/IP validatie');
define('lg_admin_settings_spamtimeipdesc','Valideert dat het via de portaal ingediende bericht niet oud is (dat wil zeggen, ingediend door een spambot) en dat het bericht afkomstig is van het IP adres waar de pagina naar toe is gestuurd. Opmerking: er is een kleine kans dat goedbedoelende klanten/gebruikers last hebben van deze instelling. Als u dit uit wilt sluiten schakelt u deze functie het beste uit.');
define('lg_admin_settings_captchatext','Text Captcha');
define('lg_admin_settings_captchare','reCaptcha Service');
define('lg_admin_settings_captcha','Captcha type');
define('lg_admin_settings_captchadesc','Vraagt de portaal gebruiker die een formulier indient om een getoond woord over te typen. Dit is om uit te sluiten dat het formulier door een bot ingediend wordt. Dit geldt voor het nieuwe aanvraagformulier en voor het forumberichtformulier.');
define('lg_admin_settings_captchawords','Tekst Captcha woorden');
define('lg_admin_settings_captchawordsdesc','De woorden die gebruikt worden in het Tekst captcha systeem. Een woord of zin per regel.');
define('lg_admin_settings_captcharedesc','reCAPTCHA is een gratis service van de Carnegie Mellon University. Deze afbeelding/geluid captcha is veiliger dan een gewone captcha. Om het te kunnen gebruiken moet u via <a href="http://recaptcha.net/whyrecaptcha.html" target="_blank">een gratis API KEY aanvragen</a>.');
define('lg_admin_settings_captcharepublic','Publieke API Key');
define('lg_admin_settings_captchareprivate','Prive API Key');
define('lg_admin_settings_captcharetheme','Visueel thema');
define('lg_admin_settings_captcharelang','Taal');
define('lg_admin_settings_captcharetheme_clean','Clean');
define('lg_admin_settings_captcharetheme_red','Red');
define('lg_admin_settings_captcharetheme_white','White');
define('lg_admin_settings_captcharetheme_blackglass','Black Glass');
define('lg_admin_settings_captcharelang_en','English');
define('lg_admin_settings_captcharelang_nl','Dutch');
define('lg_admin_settings_captcharelang_fr','French');
define('lg_admin_settings_captcharelang_de','German');
define('lg_admin_settings_captcharelang_pt','Portuguese');
define('lg_admin_settings_captcharelang_es','Spanish');
define('lg_admin_settings_captcharelang_tr','Turkish');
define('lg_admin_settings_orgname','Helpdesk naam');
define('lg_admin_settings_lang','Taal');
define('lg_admin_settings_contactvia','Default contactmethode');
define('lg_admin_settings_defaulthistorysearch','Default geschiedenis zoeken');
define('lg_admin_settings_request_search1','Algemene zoekactie');
define('lg_admin_settings_request_search2','Overeenkomst op emailadres');
define('lg_admin_settings_request_search3','Overeenkomst op volledige naam');
define('lg_admin_settings_request_search4','Overeenkomst op klant ID');
define('lg_admin_settings_request_search5','Overeenkomst op emaildomein');
define('lg_admin_settings_request_search6','Overeenkomst op achternaam');
define('lg_admin_settings_staffselectcontact','Dwing af dat de medewerker een keuze maakt');
define('lg_admin_settings_defaultemail','Default afzender');
define('lg_admin_settings_defaultemailex','De default mailbox waar vandaan publieke notities worden gestuurd bij het maken van een aanvraag');
define('lg_admin_settings_tz','Systeem tijdzone');
define('lg_admin_settings_dateformat','Datum formaat');
define('lg_admin_settings_dateformatex','Het formaat wordt beschreven in de');
define('lg_admin_settings_dateformatlink','PHP handleiding');
define('lg_admin_settings_shortdateformat','Kort datum formaat');
define('lg_admin_settings_popupcalformat','Popup kalendar datum formaat');
define('lg_admin_settings_popupcalshortformat','Popup kalender kort datum formaat');
define('lg_admin_settings_emailnotvalid','Emailadres voor notificaties is geen geldig adres');
define('lg_admin_settings_orgimg','Helpdesk afbeelding URL');
define('lg_admin_settings_orgimgex','(optioneel) Geef een volledige URL op naar een afbeelding die getoond wordt in plaats van de organisatienaam. Een transparante PNG niet groter dan 190px breed en 40px hoog wordt aanbevolen.');
define('lg_admin_settings_notname','Notificatie emailadres naam');
define('lg_admin_settings_notacct','Notificatie emailadres');
define('lg_admin_settings_notnameex','Naam die getoond wordt in emails die vanaf deze account verstuurd worden');
define('lg_admin_settings_forumemailacct','Notificatie emailadres');
define('lg_admin_settings_forumemailacctex','Het emailadres wat Helpspot zal gebruiken als "antwoord aan" wanneer notificaties verzonden worden aan abonnees van forum onderwerpen');
define('lg_admin_settings_forumname','Notificatie naam');
define('lg_admin_settings_forumnameex','De naam die mensen zullen zien in hun emailclient als ze zich abonneren op updates van een forum onderwerp');
define('lg_admin_settings_notacctex','Het emailadres wat Helpspot gebruikt als "antwoord aan" bij het verzenden van notificaties. Als u een mailbox opgeeft die aan Helpspot gekoppeld is zorgt dat ervoor dat de uitwisselingen gevolgd kunnen worden.');
define('lg_admin_settings_allow_err_rep','Foutmeldingen');
define('lg_admin_settings_allow_err_repex','Sta Helpspot toe om anonieme, generieke foutrapportages terug naar Userscape te sturen. Deze rapportages worden door Userscape gebruikt om bugs te fixen en de veiligheid en stabiliteit van Helpspot te verbeteren.');
define('lg_admin_settings_allowbatch','Batchgewijs afsluiten toestaan (filters)');
define('lg_admin_settings_allowbatchex','De optie om batchgewijs af te sluiten zal in alle filters beschikbaar zijn');
define('lg_admin_settings_allowbatchrespond','Sta batchgewijs beantwoorden toe (filters)');
define('lg_admin_settings_allowbatchrespondex','Batchgewijs beantwoorden van aanvragen toestaan in alle filters');
define('lg_admin_settings_feedsenabled','RSS feeds inschakelen');
define('lg_admin_settings_feedcopyright','RSS feeds copyright');
define('lg_admin_settings_embedmedia','Audio bestanden embedden in de aanvraag geschiedenis');
define('lg_admin_settings_daystoleavetrash','Verwijderen van trash vertragen');
define('lg_admin_settings_daystoleavetrashex','Aanvragen die in trash geplaatst zijn worden na een bepaald aantal dagen pas verwijderd');
define('lg_admin_settings_neverdeletetrash','Aanvragen die in trash geplaatst zijn nooit verwijderen');
define('lg_admin_settings_maxresults','Maximum aantal resultaten wat weergegeven wordt');
define('lg_admin_settings_maxresultsex','Beperkt het aantal aanvragen wat getoond wordt in filters en zoekresultaten');
define('lg_admin_settings_virtualarchive','Filteren binnen de voorgaande (dagen)');
define('lg_admin_settings_virtualarchiveex','Beperk de resultaten van een filter tot het aantal voorafgaande dagen wat u instelt (filters met specifieke of relatieve data worden niet beinvloed). Kies 0 om uit te schakelen.');
define('lg_admin_settings_savedraftsevery','Frequentie waarmee concepten worden opgeslagen');
define('lg_admin_settings_savedraftseveryex','Als een medewerker bezig is met het bewerken van een notitie in een aanvraag wordt het concept automatisch opgeslagen volgens de door u gestelde frequentie (in seconden)');
define('lg_admin_settings_saveattach','Opslaglocatie voor attachments');
define('lg_admin_settings_saveattachex','Geef aan waar attachments van aanvragen opgeslagen moeten worden. Opslag in de database wordt aanbevolen tenzij u een buitengewoon hoog aantal attachments heeft of buitengewoon grote attachments.');
define('lg_admin_settings_saveattach_db','HelpSpot database');
define('lg_admin_settings_saveattach_file','In mappen op een server');
define('lg_admin_settings_saveattach_path','Attachment opslagmappen');
define('lg_admin_settings_saveattach_pather','Kan niet schrijven in opgegeven opslagmap');
define('lg_admin_settings_saveattach_pathex','De map waarin attachments worden opgeslagen. Deze map moet volledig beschrijfbaar zijn voor de webserver en mag niet eindigen op een slash (bijvoorbeeld: /usr/files/helpspot). <b>De map moet buiten de webroot liggen</b>.');
define('lg_admin_settings_striphtml','Weergave van geschiedenis');
define('lg_admin_settings_htmldisplay','HTML tonen');
define('lg_admin_settings_htmlremove','HTML verwijderen');
define('lg_admin_settings_htmlescape','HTML negeren');
define('lg_admin_settings_serious','Serieuze modus');
define('lg_admin_settings_seriousex','Voorkom grappig bedoelde bijzaken, zoals bijvoorbeeld de spreuken voor een lege inbox');
define('lg_admin_settings_sppathnote','Het volledige pas naar de Aspell binary op uw server. Leeg laten om spellingscontrole uit te schakelen.');
define('lg_admin_settings_htmlallowed','Verwijder geen tags die hierboven getoond worden (deze zijn nodig om te bepalen wat genegeerd moet worden). Geef op als een lijst van tags: &lt;p&gt; &lt;br&gt; &lt;b&gt; &lt;i&gt;');
define('lg_admin_settings_wysiwyg','Gebruik de WYSIWYG editor voor de kennisbank');
define('lg_admin_settings_emailintegration','Email integratie');
define('lg_admin_settings_htmlemailsbox','HTML email');
define('lg_admin_settings_htmlemails_wysiwyg','WYSIWYG (visuele editor)');
define('lg_admin_settings_htmlemails_markdown','Opgemaakte tekst (automatisch omzetten naar HTML)');
define('lg_admin_settings_htmlemails_filterimg','Verwijder image (IMG) tags');
define('lg_admin_settings_htmlemails_filterimgex','Verwijdert image tags in HTML emails om uw systeem te beschermen tegen spammers');
define('lg_admin_settings_reply_as_public','Replies to notification emails are public');
define('lg_admin_settings_reply_as_publicex','When staff reply to an email notification about a request the reply will be forwarded through HelpSpot as a public note to the customer.');
define('lg_admin_settings_htmlemails_editor','HTML editor type');
define('lg_admin_settings_htmlemails_editorex','De WYSIWYG editor is een visuele editor die lijkt op Microsoft Word. Door u opgemaakte tekst wordt omgezet naar HTML.');
define('lg_admin_settings_htmlemails','HTML inschakelen voor notities');
define('lg_admin_settings_htmlemails_wysiwygex','Spellingscontrole wordt automatisch ingevoegd indien beschikbaar. Scheidt iedere knop met een spatie en iedere groep met een rechtstaande streep ("|").');
define('lg_admin_settings_htmlemails_wysiwyg_values','Toon geldige waarden');
define('lg_admin_settings_htmlemails_wysiwyg_row1','WYSIWYG knop rij 1');
define('lg_admin_settings_htmlemails_wysiwyg_row2','WYSIWYG knop rij 2');
define('lg_admin_settings_htmlemails_wysiwyg_row3','WYSIWYG knop rij 3');
define('lg_admin_settings_htmlemails_css','WYSIWYG aangepaste CSS Style Sheet');
define('lg_admin_settings_allowattachments','Email attachments toestaan');
define('lg_admin_settings_excludemimes','Niet toegestane attachment extensies');
define('lg_admin_settings_excludemimesex','De lijst met extensies moet komma gescheiden zijn (bijvoorbeeld:zip,exe,swf)');
define('lg_admin_settings_emailloop','Controleer op duplicaten');
define('lg_admin_settings_emailloopex','Vergelijk binnenkomende berichten met berichten uit het ingestelde voorafgaand aantal seconden. Identieke berichten in dit tijdsbestek worden genegeerd. (kies 0 om uit te schakelen)');
define('lg_admin_settings_emaildaysafter','Gesloten aanvragen voor');
define('lg_admin_settings_emaildaysafter_always','Altijd heropenen');
define('lg_admin_settings_emaildaysafter_never','Nooit heropenen');
define('lg_admin_settings_inseconds','(in seconden)');
define('lg_admin_settings_emaildaysafterex','Een aanvraag wordt altijd heropend als er een antwoord op komt, tenzij de gesloten aanvraag ouder is dan het ingestelde aantal dagen');
define('lg_admin_settings_maxattachsize','Maximale omvang van attachments');
define('lg_admin_settings_maxattachsizeex','Opmerking: grote emails hebben mogelijk extra configuratie nodig, zie <a href="http://www.userscape.com/helpdesk/index.php?pg=kb.page&id=34" target="_blank">omgaan met grote email attachments</a>.');
define('lg_admin_settings_outboundemail','Stuur uitgaande mail via');
define('lg_admin_settings_outboundemailex','SMTP wordt aanbevolen in verband met hogere zekerheid van bezorging en duidelijke foutmeldingen');
define('lg_admin_settings_smtptest','Test uitgaande email');
define('lg_admin_settings_emailmaximport','Maximaal aantal gelijktijdig op te halen emails');
define('lg_admin_settings_emailmaximportex','Deze instelling beschermt het systeem tegen het dupliceren van emails wanneer er meer emails in de box aanwezig zijn dan in 1 keer geimporteerd kunnen worden door tasks.php. Deze instelling is per mailbox.');
define('lg_admin_settings_prefix','Aanvraag ID voorvoegsel');
define('lg_admin_settings_prefixex','Een unieke set letters die toegevoegd worden aan de aanvraag ID\'s in uitgaande emails. Gebruik dit om conflicten te voorkomen als u emails uitwisselt tussen meerdere HelpSpot omgevingen. Het voorvoegsel mag alleen letters bevatten. Leeglaten om geen voorvoegsel te gebruiken.');
define('lg_admin_settings_phpmail','PHP mail functie');
define('lg_admin_settings_spamfilter','SPAM filter');
define('lg_admin_settings_spamfilterex','Opmerking:"de instelling "alleen aan voor controleren" moet alleen ingeschakeld worden als het systeem voldoende tijd heeft gehad om te leren. Doorgaans is dat enkele maanden');
define('lg_admin_settings_spamfilter_on','Aan');
define('lg_admin_settings_spamfilter_checkonly','Alleen aan om te controleren, niet om te trainen');
define('lg_admin_settings_spamfilter_off','Uit');
define('lg_admin_settings_debugtasks','Schakel debugging output in voor tasks.php');
define('lg_admin_settings_debugtasksex','Wanneer u deze optie inschakelt kunt u tasks.php in uw webbrowser bezoeken om details en informatie te zien over geimporteerde emails.');
define('lg_admin_settings_spamsettings','Instellingen voor SPAM');
define('lg_admin_settings_spam_whitelist','Whitelist');
define('lg_admin_settings_spam_whitelistex','Een email (of header string) per regel. Functie doorzoekt de hele header van de email voor overeenkomsten.');
define('lg_admin_settings_spam_blacklist','Blacklist');
define('lg_admin_settings_spam_blacklistex','Een email (of header string) per regel. Functie doorzoekt de hele header van de email voor overeenkomsten.');
define('lg_admin_settings_loopnew','Lus preventie voor nieuwe aanvraag');
define('lg_admin_settings_loopnewex','Deze instelling voorkomt dat de emailbox auto replies blijft genereren in een lus situatie. Als voldaan wordt aan de voorwaarden die hieronder genoemd worden dan wordt auto reply uitgeschakeld voor dat emailadres, totdat niet meer aan de voorwaarden voldaan wordt.');
define('lg_admin_settings_loopnewtime','Periode');
define('lg_admin_settings_loopnewtimeex','Kijk terug over deze periode terug of er lussen geweest zijn.');
define('lg_admin_settings_loopnewct','Maximaal aantal emails in deze periode');
define('lg_admin_settings_loopnewctex','Het aantal emails van 1 adres binnen de periode wat de grenswaarde is voor het automatisch inschakelen van lus preventie.');
define('lg_admin_settings_min','Minuten');
define('lg_admin_settings_hour','Uur');
define('lg_admin_settings_hours','Uren');
define('lg_admin_settings_globalbcc','Globale BCC');
define('lg_admin_settings_globalbcc_note','Een emailadres wat BCC\'s ontvangt vanuit het systeem');
define('lg_admin_settings_globalbcc_typeall','Alle uitgaande emails');
define('lg_admin_settings_globalbcc_typepublic','Alleen publieke notities aan klanten');
define('lg_admin_settings_replyabove','Antwoord hierboven tekst');
define('lg_admin_settings_replyaboveex','De regel die automatisch in elke email ingevoegd wordt om te voorkomen dat Helpspot het antwoord van uw klant niet kan herleiden');
define('lg_admin_settings_emailopt','Algemene email instellingen');
define('lg_admin_settings_smtpconf','SMTP configuratie');
define('lg_admin_settings_smtp','SMTP server(s)');
define('lg_admin_settings_smtpauth','Gebruik SMTP authenticatie');
define('lg_admin_settings_smtpproto','SMTP security protocol');
define('lg_admin_settings_smtpprotoex','Voor de meeste installaties is <b>geen</b> de beste optie. OpenSSL moet ingeschakeld zijn in PHP voor beveiligde verbindingen.');
define('lg_admin_settings_smtpprotolabeldefault', 'Default (Use these if unsure)');
define('lg_admin_settings_smtpprotolabeladvanced', 'Advanced (If the mail server requires a specific protocol)');
define('lg_admin_settings_smtpprotonone','Geen');
define('lg_admin_settings_smtpprotossl','SSL');
define('lg_admin_settings_smtpprototls','TLS');
define('lg_admin_settings_smtpprototlsv12','TLS v1.2');
define('lg_admin_settings_smtphost','SMTP host');
define('lg_admin_settings_smtphostex','URL van de SMTP server. Meerdere servers kunt u als volgt opgeven: smtp.example.com;smtp2.example.com');
define('lg_admin_settings_smtpuser','SMTP username');
define('lg_admin_settings_smtppass','SMTP password');
define('lg_admin_settings_smtppass_msg','Leave blank unless changing');
define('lg_admin_settings_smtptimeout','SMTP Timeout');
define('lg_admin_settings_smtphelo','SMTP HELO');
define('lg_admin_settings_smtpheloex','Dit wordt meestal leeg gelaten');
define('lg_admin_settings_smtpport','SMTP poort');
define('lg_admin_settings_livelookup','Live Lookup');
define('lg_admin_settings_livelookupex','Live Lookup stelt u in staat om realtime klantinformatie vanuit een andere bron naar HelpSpot te halen.');
define('lg_admin_settings_livelookupexinst','Instructies');
define('lg_admin_settings_uselivelookup','Live Lookup ingeschakeld');
define('lg_admin_settings_charencoding','XML karakter codering');
define('lg_admin_settings_charencodingex','De karakter codering die gebruikt wordt voor de XML die Live Lookup terugstuurt. Vanwege beperkingen in PHP zijn alleen deze drie keuzes mogelijk.');
define('lg_admin_settings_lltype','Lookup via');
define('lg_admin_settings_llpath','Live Lookup bron');
define('lg_admin_settings_lladd','Een bron toevoegen');
define('lg_admin_settings_llpathtoscript','Pad naar script');
define('lg_admin_settings_llsearchname','Zoeknaam');
define('lg_admin_settings_llsearchnameex','Bijvoorbeeld: Unit4 Multivers, Active Directory, CRM ABC');
define('lg_admin_settings_lltypeex','Live lookups kunnen via de opdrachtprompt of in HTML uitgevoerd worden');
define('lg_admin_settings_llpathex','Volledig pad naar het bestand wat de XML genereert. Als u HTML gebruikt dan moet het pad beginnen met http://');
define('lg_admin_settings_llauto','Automatisch uitvoeren');
define('lg_admin_settings_llautoex','Voer Live Lookup atomatisch uit als een medewerker het aanvraagscherm opvraagt en het hierboven genoemde veld leeg is. Zoekbron nummer 1 wordt altijd gebruikt.');
define('lg_admin_settings_llautonorun','Niet automatisch uitvoeren');
define('lg_admin_settings_ws','Web service API');
define('lg_admin_settings_wsex','Toegang tot HelpSpot via de API. Maak aanvragen aan, draai filters en meer.');
define('lg_admin_settings_wsexinst','Instructies');
define('lg_admin_settings_wspub','Publieke API');
define('lg_admin_settings_wspriv','Prive API');
define('lg_admin_settings_wspubcols','Publieke API resultaatkolommen');
define('lg_admin_settings_wspubcolsex','De data kolommen die iedere publieke API methode teruggeeftThe data columns each public API method als resultaat.');
define('lg_admin_settings_cmd','Opdrachtprompt');
define('lg_admin_settings_http','HTTP(s) - via GET');
define('lg_admin_settings_httppost','HTTP(s) - via POST');
define('lg_admin_settings_forums','Forums');
define('lg_admin_settings_pagesize','Onderwerpen per pagina');
define('lg_admin_settings_enablepubforumfeeds','RSS feeds ingeschakeld');
define('lg_admin_settings_feedsize','ONderwerpen in de RSS Feed');
define('lg_admin_settings_closeafter','Sluit onderwerpen na');
define('lg_admin_settings_kb','Kennisbank onderdelen');
define('lg_admin_settings_wysiwygstyle','WYSIWYG aangepaste stylesheet');
define('lg_admin_settings_styleex','CSS stijlen die u hier toevoegt zullen beschikbaar zijn in de WYSIWYG editor. Gebruik deze optie om de vormgeving van uw paginas consistent te houden.');
define('lg_admin_settings_portal','Portal');
define('lg_admin_settings_terms_enable','Ask customer to accept privacy policy and terms');
define('lg_admin_settings_portalterms','URL of terms of service');
define('lg_admin_settings_portal','Portaal');
define('lg_admin_settings_portalphone','Telefoonummer voor support');
define('lg_admin_settings_portalphoneex','De waarde die u hier invult zal getoond worden onderin de portaalpaginas');
define('lg_admin_settings_portalphoneex','Filling this in will add the phone number to the bottom of the portal navigation');
define('lg_admin_settings_portalmsg','Portaal homepage bericht (HTML toegestaan)');
define('lg_admin_settings_formformat','Format voor het aanvraagforumlier op de portaal');
define('lg_admin_settings_formformatex','Het gedetailleerde format biedt uw klanten meer structuur bij het geven van de juiste informatie over hun aanvraag');
define('lg_admin_settings_autoreply','Automatisch antwoord voor aanvragen die via de portaal komen');
define('lg_admin_settings_autoreplyex','Wilt u dat de klant een automatisch antwoord per email ontvangt na het indienen van een aanvraag via de portaal');
define('lg_admin_settings_detailedformat','Gedetailleerd format (3 vragen)');
define('lg_admin_settings_simpleformat','Eenvoudig format (een enkel tekstvak)');
define('lg_admin_settings_allowuploads','Attachments toestaan');
define('lg_admin_settings_portalsearchontype','Toon de aanvraag geschiedenis op basis van');
define('lg_admin_settings_portalsearchontypeex','Als een klant inlogt om zijn of haar aanvraag geschiedenis te bekijken, alles tonen voor hun emailaccount of voor iedere Klant ID die verbonden is met dat emailadres. De andere optie wordt gebruikt om alle medewerkers van een organisatie toe te staan om aanvragen in te dienen namens die organisatie.');
define('lg_admin_settings_portalsearchontypeemail','Email account');
define('lg_admin_settings_portalsearchontypeid','Klant ID\'s die verbonden zijn met een email account');
define('lg_admin_settings_portalauthtype','Aanvraag geschiedenis login type');
define('lg_admin_settings_portalauthtypeex','Het type authenticatie wat gebruikt moet worden om in te loggen op de aanvraag geschiedenis. Black Box stel u in staat om de logins van uw medewerkers op uw eigen omgeving te gebruiken. Kijk voor meer informatie <a href="http://www.userscape.com/helpdesk/index.php?pg=kb.page&id=186">hier</a>.');
define('lg_admin_settings_portalauthtypebb','Black Box');
define('lg_admin_settings_portalauthtypeint','HelpSpot intern');
define('lg_admin_settings_portalauthtypebbex','Om Black Box te kunnen gebruiken moet het bestand BlackBoxPortal.php in uw /custom_code/ map aanwezig zijn.');
define('lg_admin_settings_bizhours','Kantooruren');
define('lg_admin_settings_bizhours_start','Start');
define('lg_admin_settings_bizhours_end','Einde');
define('lg_admin_settings_bizhours_nohours','Niet werkdag');
define('lg_admin_settings_bizhours_holidays_label','Feestdagen en vakanties');
define('lg_admin_settings_bizhours_holidays_erdate','Deze datum bestaat al');
define('lg_admin_settings_bizhours_holidays_desc','Als u een feestdag invoert dan wordt deze datum niet beschouwd als kantooruur. De feestdag markeren als Niet werkdag betekent dat er kantooruren in deze dag zijn.');
define('lg_admin_settings_bizhours_date','Datum');
define('lg_admin_settings_monday','Maandag');
define('lg_admin_settings_tuesday','Dinsdag');
define('lg_admin_settings_wednesday','Woensdag');
define('lg_admin_settings_thursday','Donderdag');
define('lg_admin_settings_friday','Vrijdag');
define('lg_admin_settings_saturday','Zaterdag');
define('lg_admin_settings_sunday','Zondag');
define('lg_admin_settings_bizhours_error','Een van de kantoortijden heeft een eindtijd die voor de begintijd ligt.');
define('lg_admin_settings_prefix_error','Het email voorvoegsel mag alleen letters bevatten');
define('lg_admin_settings_allow_cc','Allow CC email addresses');
define('lg_admin_settings_allow_subject','Allow customer defined subject');

/* HelpSpot 5 Additions */
define('lg_admin_settings_saml', 'SAML2.0');
define('lg_admin_settings_saml_usernamenote', 'Your staff must have a SAML username (or email) set in their HelpSpot settings in order to login');
define('lg_admin_settings_saml_idp', 'Identity Provider (IdP)');
define('lg_admin_settings_saml_entityid', 'Entity ID');
define('lg_admin_settings_saml_entityid_ex', 'The Identity Provider identity (issuer) URL');
define('lg_admin_settings_saml_loginurl', 'Login URL (SSO)');
define('lg_admin_settings_saml_loginurl_ex', 'The Identity Provider SSO login URL');
define('lg_admin_settings_saml_logouturl', 'Logout URL (SLO)');
define('lg_admin_settings_saml_logouturl_ex', 'The Identity Provider SLO logout URL');
define('lg_admin_settings_saml_cert', 'Certificate');
define('lg_admin_settings_saml_cert_ex', 'Must be x509 certificate format. Microsoft users can find this within the Federation Metadata XML.');
define('lg_admin_settings_saml_sp', 'Service Provider (SP)');
define('lg_admin_settings_saml_sp_ex', 'Use the following information to complete any needed configuration within your Identity Provider (IdP).');
define('lg_admin_settings_saml_relaystate', 'Relay State');
define('lg_admin_settings_saml_acs', 'Assertion Consumer Service (ACS) URL');
define('lg_admin_settings_saml_signonurl', 'Login URL');
define('lg_admin_settings_saml_signouturl', 'Single Logout Service (SLS) URL');
define('lg_admin_settings_portalauthtypesamlex', 'Use SAML for Portal authentication.');
define('lg_admin_portals_require_auth', 'Require Portal Authentication');
define('lg_admin_portals_require_auth_ex', 'Users will not be able to submit requests or browse knowledge bases until they login');
define('lg_admin_settings_workers', 'Workers');
define('lg_admin_settings_workers_restart', 'Restart Workers');
define('lg_admin_settings_workers_restart_info', 'This will restart your queue workers');
define('lg_admin_settings_workers_restarted', 'The workers have been restarted');
define('lg_admin_settings_sesstimeout','Session Timeout');
define('lg_admin_settings_sesstimeoutex','Length of login session before user is logged out');
define('lg_admin_settings_terms_enable','Ask customer to accept privacy policy and terms');
define('lg_admin_settings_portalterms','URL of terms of service');
define('lg_admin_settings_portalprivacy','URL of privacy policy');
define('lg_admin_settings_portalterms_info','If you enter a URL, then the users must accept before submitting a request');
define('lg_admin_settings_reply_above_slash_error', 'The reply above text can not contain a slash `/`');

